### ISSUE TITLE
Dedicated logging

### ISSUE THREAD

**Issue by jamesgeer** [jamesgeer/conf-twitter-bot#34]
As the application grows, keeping everything as a "console log" can lead to information being missed, or make it tedious to scroll around to find the error within the terminal or specific output so it could be wise to store logs.

I'm not too familiar with the best logging practices but I came across this library that seems nice: [pino](https://www.npmjs.com/package/pino) do some research/investigation or use a library you think is better, or no library at all if you think the logs should be dumped to a file/database.

Links:
https://www.npmjs.com/package/pino
https://getpino.io

**Comment by EdwardChristian** [comment]
Started work on this, will log actions to a separate file
