### ISSUE TITLE
Button still says "Sign in" after signing in

### ISSUE THREAD

**Issue by EdwardChristian** [jamesgeer/conf-twitter-bot#44]
If you are already a signed in user and click the sign in button, the form for signing in appears and  you can basically sign in again (useless action)

To fix this, we should hide the sign in button if the user is signed in and make sure we check for a signed in user whenever the sign in form page is loaded.

**Comment by jamesgeer** [comment]
Change button to say "logout" and send a post request to '/api/sessions/logout' located in sessions.route.to.
