### ISSUE TITLE
Add KAR as data source

### ISSUE THREAD

**Issue by jamesgeer** [jamesgeer/conf-twitter-bot#53]
Imported from https://github.com/smarr/conf-twitter-bot/issues/10

At https://kar.kent.ac.uk/, we maintain a list of all publications.

Would be great to be able to scrap those (there might be an API), and would be even better if it could be monitored regularly, to notify the user about new papers.

The idea here would be to advertise the papers of the school or at least the Programming Languages and Systems group regularly.

**Comment by EdwardChristian** [comment]
https://kar.kent.ac.uk/view/people/27935.html

useful link
